pom.xml, src/main/java/org/vaadin/addons/ai/formfiller/FormFiller.java, src/test/java/org/vaadin/addons/ai/formfiller/utils/OCRUtils.java
As Knoobie suggested the dependency was removed from pom.xml and also the code was refactored wherever the GSON was used before, so in these classes:
- `src/main/java/org/vaadin/addons/ai/formfiller/FormFiller.java`
- `src/test/java/org/vaadin/addons/ai/formfiller/utils/OCRUtils.java`
I have tested with:
- on the `localhost:8080` (text fillign)
- and with two invoices `localhost:8080/invoices` pages (a Hungarian and an English invoices, did not see any errors, problems, the automatic fillings were working as expected)
Fixes # (issue):
- https://github.com/vaadin/form-filler-addon/issues/30
=> chore: Replacing GSON with Jackson usage/library and removing the GSON dependency from POM as well.

src/main/java/org/vaadin/addons/ai/formfiller/FormFiller.java, src/main/java/org/vaadin/addons/ai/formfiller/utils/ComponentUtils.java, src/test/java/org/vaadin/addons/ai/formfiller/views/FormFillerInvoiceDocDemo.java, src/test/java/org/vaadin/addons/ai/formfiller/views/FormFillerReceiptDocDemo.java, src/test/java/org/vaadin/addons/ai/formfiller/views/FormFillerTextDemo.java
**Changes:**
- Adding fallback to handle all components if those have `HasValue()`, and try to fill them with `setValue(String s)`;
- Adding more meaningful logging, when does not find any components with this log message:
` logger.warn("Component type not supported: {}", componentInfo.component.getClass().getSimpleName());`
- https://github.com/vaadin/form-filler-addon/issues/40
And improving:
- https://github.com/vaadin/form-filler-addon/issues/49
=> feat:  adding support for more components (IntegerField, EmailField, PasswordField, BigDecimalField), 

src/main/java/org/vaadin/addons/ai/formfiller/services/ChatGPTChatCompletionService.java
Changed model used in ChatGPTChatCompletionService to an static model to avoid unpredictable results when OpenAI updates the models.
Fixes #60
=> Changed ChatGPTChatCompletionService model to an static model

src/main/java/org/vaadin/addons/ai/formfiller/FormFiller.java, src/main/java/org/vaadin/addons/ai/formfiller/services/ChatGPTService.java
After DX investigation it was shown that is a problem that ChatGPTService is responding JSON with keys without double quotes. When id contains spaces this ends on a JSON mapping error. 
Also a new constructor has been added to FormFiller with target/LLMservice as it seems convenient after DXs
Fixes #58
=> Improved prompt for ChatGPTService to guarantee correct JSON response (and new constructor was added to FormFiller)

src/main/java/org/vaadin/addons/ai/formfiller/utils/ComponentUtils.java
When a field inspected (part of the target) has no id defined there is a log message output. To avoid false positive messages with components inside the target that are not meant to be filled there is a new method with supported components. This makes components such as Layouts or RadioButtonItem (internal) not producing false positives. 
Fixes #52
=> Added log message when a inspected supported field has no id defined

src/main/java/org/vaadin/addons/ai/formfiller/utils/ComponentUtils.java
The Bean class used in the grid requires and empty public constructor. So a detailed message has been added when the bean instance creation fails. 
Fixes #55
=> Added detailed info when Bean instance creation fails

pom.xml
Also pins the jackson library to latest version, because gpt has a transitive old dependency on it.
=> chore: Upgrade gpt version to latest

src/main/java/com/vaadin/flow/ai/formfiller/utils/ComponentUtils.java
Column is now managed inside the Grid process without the requirement of setting Ids to be registered in the FormFiller as now FormFiller works with the Bean of the Grid instead of with the columns Ids. 
Fixes #75 
Fixes #2
=> fix: removed Column from supported components as id is not longer required for them.

src/main/java/com/vaadin/flow/ai/formfiller/utils/ComponentUtils.java, src/test/java/com/vaadin/flow/ai/formfiller/data/OrderItem.java, src/test/java/com/vaadin/flow/ai/formfiller/utils/Converters.java, src/test/java/com/vaadin/flow/ai/formfiller/views/FormFillerTextDemo.java
**Changes:**
- Added Date field to OrderItem,
- Added checking and parsing it to ComponentUtils,
- And added an example to FormFillerTextDemo,
- https://github.com/vaadin/form-filler-addon/issues/51
=> feat: added Date support to Grid, now a bean can have a Date field types.

src/main/java/com/vaadin/flow/ai/formfiller/utils/ComponentUtils.java, src/test/java/com/vaadin/flow/ai/formfiller/views/FormFillerTextDemo.java
Reviewed and fixed the multi-select combobox to make it possible to fill it with the auto filler.
- https://github.com/vaadin/form-filler-addon/issues/53
**Changes:**
- Based on the checkboxgroup rewritten, updated the code (instruction and filling)
- Added example as well to the FormFillerTextDemo class (same example as RadioButton group, so the services)
**Also:**
- `joiner.toString()` -> `joiner` as it is not needed for the String concatenation.
- `Set<String> set = new HashSet<String>(list);` ->  `Set<String> set = new HashSet<>(list);`
=> feat: make MultiSelectCombobox supported for the form filler.

pom.xml
Uses latest versions with no known vulnerabilities
=> chore: Override okhttp versions with latest

pom.xml
Based on Marc's problem:
```
Failed to collect dependencies at com.vaadin.flow.ai:form-filler-addon:jar:0.1.0: Failed to read artifact descriptor for com.vaadin.flow.ai:form-filler-addon:jar:0.1.0: Could not find artifact com.vaadin:vaadin-bom:pom:24.1-SNAPSHOT
```
and Artur's recommended way to handle Vaadin versions.
This will solve the problem, when a developer is adding the `form-filler-addon` dependency to a maven project and having a specific `vaadin-core` version, now with this, the version should come from the project the addon dependency is used.
Fixes # (issue):
- https://github.com/vaadin/form-filler-addon/issues/122
=> chore: changing vaadin-core dependency to have provided scope.

pom.xml
this allow us to do the prerelease update dropping the staging feature
=> update vaadin-parent to 2.2.0

pom.xml, src/main/java/com/vaadin/flow/ai/formfiller/utils/ComponentUtils.java, src/test/java/com/vaadin/flow/ai/formfiller/utils/ComponentUtilsTest.java, src/test/java/com/vaadin/flow/ai/formfiller/views/FormFillerTextDemo.java
Based on slack discussions (Leif's suggestions): values can only be AI-filled into ComboBoxes and MultiSelectComboBoxes, if:
- The values are already present in the items list
OR
- The values aren't in the items list, but the 'allow custom values' option is set to true.
- https://github.com/vaadin/form-filler-addon/issues/125
=> fix: filling values for ComboBoxes and MultiSelectComboboxes.

README.md, pom.xml
Adding a development profile which should be used in order to properly run the addon project with reachable demos:
- http://localhost:8080, 
- http://localhost:8080/receipt 
- http://localhost:8080/invoice
The proper mvn command:
```
mvn jetty:run -Pdevelopment
```
Otherwise if no development used then only Jetty context is reachable:
Server logs quite empty, no Vaadin server related load there:
```
...
[WARNING] jakarta.servlet.http.WebConnection scanned from multiple locations: jar:file:///Users/pczuczor/.m2/repository/org/eclipse/jetty/toolchain/jetty-jakarta-servlet-api/5.0.2/jetty-jakarta-servlet-api-5.0.2.jar!/jakarta/servlet/http/WebConnection.class, jar:file:///Users/pczuczor/.m2/repository/jakarta/servlet/jakarta.servlet-api/5.0.0/jakarta.servlet-api-5.0.0.jar!/jakarta/servlet/htt …
```
=> fix: add the development profile, which is required to access the demo URLs.

pom.xml, src/main/java/com/vaadin/flow/ai/formfiller/utils/ComponentUtils.java, src/test/java/com/vaadin/flow/ai/formfiller/utils/ComponentUtilsTest.java, src/test/java/com/vaadin/flow/ai/formfiller/views/FormFillerTextDemo.java
Cherry-pick from:
- #128 
---From previous PR----
Based on Slack discussions (Leif's suggestions): values can only be AI-filled into ComboBoxes and MultiSelectComboBoxes, if:
- The values are already present in the items list
OR
- The values aren't in the items list, but the 'allow custom values' option is set to true.
- https://github.com/vaadin/form-filler-addon/issues/125
=> fix: filling values for ComboBoxes and MultiSelectComboboxes. (#128) (CP: 0.1)

README.md, pom.xml
We discussed to not having specific, unique build configs, because harder to maintain or keep in mind.
The following changes happened/happening here:
- profile renamed  `development` -> `dev`
- the dev profile is not activate by default anymore
- README.md changes related to the previous points, 
- **build config** reverted back the changes in the 3. steps mvn clean install build, so removing the profile skip
(delete `-P-development` from parameters list)
The changes were tested and `mvn clean install` and both `mvn -Pdev` work perfectly)
Referring to this PR:
- https://github.com/vaadin/form-filler-addon/pull/129
- and our Slack discussions with Mikhail
=> fix: pom.xml development/dev profile related changes.

src/main/java/com/vaadin/flow/ai/formfiller/utils/KeysUtils.java
Checks that the key from system property is not blank.
The demo project sets in to an empty string by default, so that lead to a false positive check.
Fixes https://github.com/vaadin/form-filler-demo/issues/5
=> fix: Check if key is blank

src/main/java/com/vaadin/flow/ai/formfiller/services/ChatGPTService.java
From the OpenAI documentation:
- https://platform.openai.com/docs/guides/text-generation
None of the other models mentioned were able to function, except this `gpt-3.5-turbo-instruct` appears to work and is capable of producing a JSON response.
With this change, we can also use the `/` (text to fill) example and the ChatGPT Service.
So this is also a solution and maybe even better than #149
=> fix: Changed the ChatGPTService model to gpt-3.5-turbo-instruct.

pom.xml
`io.github.classgraph:classgraph:jar:4.8.21:compile` has been reported with CVE-2021047621
as `com.theokanning.openai-gpt3-java:service:jar:0.16.0` is already end-of-support, let us exclude the vulnerable dep and upgrade it  separately.
=> get rid of CVE-2021-47621
